# Generated by Django 3.2.8 on 2021-10-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumanji', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciality',
            new_name='Specialty',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
