# Generated by Django 3.2.8 on 2021-11-07 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jumanji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NOT', 'Не ищу работу'), ('CONS', 'Рассматриваю предложения'), ('LOOK', 'Ищу работу')], default='LOOK', max_length=4)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[('TR', 'Стажер'), ('JUN', 'Джуниор'), ('MID', 'Миддл'), ('SEN', 'Сеньор'), ('LEAD', 'Лид')], default='MID', max_length=4)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jumanji.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
